version: "2"

services:
  spark:
    image: docker.io/bitnami/spark:3.1.2
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '9090:8080'
  spark-worker:
    image: docker.io/bitnami/spark:3.1.2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  master:
    image: modenaf360/hadoop-3.2:latest
    container_name: master
    hostname: master
    volumes:
      - ./data/masterdata:/hadoop/dfs/name
      - ./data/datanode:/hadoop/dfs/data
    environment:
      - CLUSTER_NAME=test
      - NODE_TYPE=namenode
      - GOTTY_ID=modenaf360
      - GOTTY_PW=1234
    env_file:
      - hadoop.env
    ports:
      - 8989:7777
      - 50070:50070/tcp
      - 8042:8042/tcp
      - 8085:8080/tcp
      - 8985:8085/tcp
      - 8088:8088/tcp
      - 9000:9000/tcp
      - 8031:8031/tcp
      - 19888:19888/tcp
