# Doesn't do anything yet
name: Release

on:
  release:
    types: [ published ]

  workflow_dispatch:
    inputs:
      rebuild:
        description: 'A tag name for building previously created release'
        required: false
        default: '0.0.0'
      buildOptions:
        description: 'Additional options for Gradle build command'
        required: false
        default: ''

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build