# Doesn't do anything yet
name: Release

on:
  release:
    types: [ published ]

  workflow_dispatch:
    inputs:
      rebuild:
        description: 'A tag name for building previously created release'
        required: false
        default: '0.0.0'
      buildOptions:
        description: 'Additional options for Gradle build command'
        required: false
        default: ''

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
          cache: gradle

      - name: Build JAR file with Gradle
        run: ./gradlew build -Pversion=${{ github.event.release.tag_name }}

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          file: build/libs/odd-spark-adapter-${{ steps.build.outputs.version }}.jar
          tag: ${{ github.event.release.tag_name }}
