name: Release
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump package version
        run: |
          docker run --rm \
            -v $PWD:/src \
            -w /src \
            tomologic/bumpversion --current-version $(cat VERSION) patch VERSION
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew jar
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs
      - name: Update repository with up-to-date submodules and version
        run: |
          git config --global user.email "opendatadiscovery-bot@provectus.com"
          git config --global user.name "OpenDataDiscovery Bot"
          if [ -n "$(git status --porcelain)" ]
          then
            git add .
            git commit -m "Bump package version"
            git push origin main
          fi
